- makefile
Without this change, the `make test` command will fail if there is more
than one `**/*_test.go` file, because `dirname` takes one and only one
argument. This was not a problem in #10 because there was only one test
file.
> Fix the `make test` makefile target

- pkg/environment/common.go
- pkg/environment/fixtures/foobar-namespace.yml
- pkg/environment/namespace.go
- pkg/environment/namespace_test.go
- pkg/environment/repoEnvironment.go
- pkg/environment/repoEnvironment_test.go
- pkg/environment/templateEnvironment.go
- pkg/environment/templateEnvironment_test.go
- pkg/environment/templatesRds.go
This PR mainly moves existing functionality into different, more tightly-scoped, files. This should make it easier to maintain the code as we extend the cli tool. It also:
* adds basic tests for the new files
* uses constants instead of hard-coded string values
* uses relative rather than absolute file paths, where possible (to make testing easier)
* changes some function names for clarity
> Restructure the code to make it more testable

- .github/workflows/build-release.yml
- cmd/cloud-platform/.goreleaser.yml
This adds a windows build, which was missing before
co-authored with @mogaal
> Add explicit build instructions for all platforms

- .github/workflows/build-release.yml
This reverts commit 91c2736d90f5134b64432ed8a70029508c1fad62.
This didn't work, and it broke the release process. But even without it,
we get a "Changelog" in the release description, which is good enough
for now.
> Revert "Add CHANGELOG to release package"

- README.md
These instructions are for a mac, which is called out in the copy. MoJ
developers who are using a different computer should be a) rare, and b)
used to having to figure out different installation instructions.
> Add instructions for installing the binary

- .github/workflows/run-tests.yml
- cmd/cloud-platform/.goreleaser.yml
As far as we know, we have no windows users, so
the extra overhead of maintaining working tests
and builds for windows is wasted.
This change removes the windows platform (we can
put it back again if we ever need it)
> Stop building & testing a windows version

- pkg/commands/environment.go
- pkg/environment/templatesS3.go
- pkg/environment/templatesS3_test.go
This PR adds "environment s3 create". 
This feature will allow users to create a standard s3 bucket to use within their namespace using the cloud-platform cli.
This PR also contains a test file to simulate and check the functionality of the createFile function.
> Add "Create S3" command to cloud-platform  cli

- pkg/environment/templateEnvironment.go
- pkg/environment/templateEnvironment_test.go
This change causes the team name to be lower-cased
before we write the rbac.yaml and variables.tf
files.
This fixes a problem later on, when the user tries
to create an ECR - if they have upper-case letters
in their team name, the ECR name generated by our
terraform module will be rejected.
NB: This change is not tested by the unit tests, 
since those don't cover the relevant part of the
code.
> Store lower-case team name, when creating NS

- pkg/commands/version.go
- pkg/environment/templateEnvironment.go
- pkg/environment/templateEnvironment_test.go
Due to the hard AWS limit creating an ingress controller per namespace
is no longer viable. This commit removes the creation of an ingress.tf
file.
> Remove ingress creation from environment create command

- makefile
Without this,`go mod download` can result in errors like:
```
github.com/hashicorp/hcl/hcl/parser
../../go/pkg/mod/github.com/hashicorp/hcl@v1.0.0/decoder.go:12:2: module github.com/hashicorp/hcl@latest found (v1.0.0), but does not contain package github.com/hashicorp/hcl/hcl/parser
../../go/pkg/mod/github.com/spf13/viper@v1.6.1/viper.go:39:2: module github.com/hashicorp/hcl@latest found (v1.0.0), but does not contain package github.com/hashicorp/hcl/hcl/printer
../../go/pkg/mod/github.com/hashicorp/hcl@v1.0.0/hcl/ast/ast.go:9:2: module github.com/hashicorp/hcl@latest found (v1.0.0), but does not contain package github.com/hashicorp/hcl/hcl/token
make: *** [cloud-platform] Error 1
```
> Add `export GO111MODULE=on`

- pkg/environment/slackChannelValidator.go
- pkg/environment/templateEnvironment_test.go
**Changes**
- allow for slack channel values to have underscores
NB: I'm not familiar with go, but attempted to change a value in the tests to verify this. This may want breaking into its own test
> 🐛 allow underscore in slack regex

- Dockerfile
Helm is not found anymore in this URL, therefore the Docker Build is failing.
Copied Helm install from tools image and just tested it builds:
```
Removing intermediate container 577fe3c647d7
---> 66e99515756b
Successfully built 66e99515756b
Successfully tagged test:latest
```
> Fix Dockerfile, helm is not found anymore in this URL. Copied line from tools-image

- pkg/terraform/utils_test.go
This tests confirms given a file directory in a text file, the
targetDirs function will extract the directory path successfully.
> Create unit test for targetDirs function

- pkg/commands/terraform.go
- pkg/terraform/terraform.go
- Renamed BulkTfPlanPaths to `BulkTfPlanPaths`. From now on, it doesn't apply for `Plan` but also `Apply`
- **Added BulkApply**. It was also possible to reuse the same BulkPlan function using the same function and passing an argument with the action (plan or apply). I decided to split it to keep it simple and also to be able to customise [1] each of them individually without adding complicated logic. This can be changed in the future. 
[1] Here customize might means: 
- I want to show the terraform init output for apply but not for plan. 
- I don't want to "cut" the refresh state output for apply (only for plan)
- etc
> Added Bulk apply capability

- pkg/commands/version.go
The current release is 1.6.1, but the code specifies 1.6.0. This means
users cannot use the cli tool because it goes into an endless upgrade
loop.
This change sets the version to 1.6.2, and a release with that version
will be created as soon as this change is merged.
> Set version to 1.6.2

- pkg/commands/version.go
- pkg/terraform/terraform.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7c1c08]
goroutine 1 [running]:
github.com/ministryofjustice/cloud-platform-cli/pkg/terraform.(*Commander).CheckDivergence(0xc0000ce2c0, 0xc000000004, 0xc00011fbc8)
/build/pkg/terraform/terraform.go:150 +0x208
github.com/ministryofjustice/cloud-platform-cli/pkg/commands.addTerraformCmd.func1(0xc000120a00, 0xc00009cc60, 0x0, 0x2)
/build/pkg/commands/terraform.go:31 +0x15a
github.com/spf13/cobra.(*Command).execute(0xc000120a00, 0xc00009cc20, 0x2, 0x2, 0xc000120a00, 0xc00009cc20)
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000120500, 0xc000120500, 0x43b3da, 0xcf8840) …
```
> Fixed in divergence output bug

- .github/workflows/sonar-scan.yml
- pkg/commands/commands.go
- pkg/commands/decodeSecret.go
- pkg/commands/version.go
- pkg/decodeSecret/decodeSecret.go
- pkg/decodeSecret/decodeSecret_test.go
This PR adds the ability to run:
```
cloud-platform decode-secret -n mynamespace -s secret
```
The output is a pretty-printed JSON representation of the secret, with the values of the data keys base64 decoded.
> Add feature - decode k8s secrets

- cmd/cloud-platform/.goreleaser.yml
I noticed the Linux binary wasn't working so I changed the structure of the GoReleaser config. This now also creates a Windows binary and will produce a changelog in the release.
> Change GoReleaser config to inc Windows and changelog

- pkg/commands/decodeSecret.go
- pkg/commands/version.go
- pkg/decodeSecret/decodeSecret.go
- pkg/decodeSecret/decodeSecret_test.go
This allows the user to run commands like this:
```
eval $(cloud-platform decode-secret -n poornima-dev -s wplearndev-rds-output -e)
aws rds describe-db-instances --db-instance-identifier=cloud-platform-xxxxxxxx
```
i.e. it incorporates the functionality of [this gist](https://gist.github.com/digitalronin/542c001f9db4ced79ebc0f180d36b609) directly into the CLI tool
> Add `decode-secret ... -e` to export AWS creds

- cmd/cloud-platform/main.go
- pkg/commands/version.go
The automatic update feature of the CLI tool means
that all pipelines which use the tool will break
whenever a new version is released. 
This change allows us to add 
`--skip-version-check` to all pipeline commands, 
so that the pipeline runs correctly regardless of
any new releases of the CLI tool.
NB: Merging this change will break our pipelines
again, but hopefully for the last time.
> Enable `--skip-version-check` for pipeline use

- pkg/commands/environment.go
- pkg/commands/version.go
- pkg/environment/templateServiceaccount_test.go
- pkg/environment/templateServiceacount.go
This alters the cli tool to create a serviceaccount as `resources/serviceaccount.tf`, by copying [this file](https://raw.githubusercontent.com/ministryofjustice/cloud-platform-terraform-serviceaccount/main/template/serviceaccount.tmpl), instead of using the previous YAML template.
> Please create release 1.7.2 after merging this PR
> Create serviceaccount via terraform

- pkg/commands/environment.go
- pkg/commands/version.go
- pkg/environment/common.go
- pkg/environment/inListValidator.go
- pkg/environment/namespace.go
- pkg/environment/prototype.go
- pkg/environment/templateEnvironment.go
- pkg/environment/templatePrototype.go
- pkg/environment/templatePrototype_test.go
- pkg/environment/templateServiceacount.go
- pkg/environment/templatesEcr.go
- pkg/environment/templatesS3.go
This adds a new feature to the CLI:
```
cloud-platform environment prototype create
```
This creates a namespace and a linked github repository with the gov.uk prototype kit, which automatically deploys any changes to the namespace via github actions.
- Remove `-n circleci` from serviceaccount help text
- Add a stub command for creating a prototype site
- Move a misplaced comment
- WiP: Prompt the user for prototype details
- Add Prototype struct, encapsulating the Namespace
- Ask user for basic auth credentials
- Add basic auth values to resources/variables.tf
- Add ECR & serviceaccount to prototype namespace
- Add tests for protoype
- Add copyUrlToFile function
- Create ecr.tf and serviceaccount.tf for prototype
- Create resources/github-repo.tf for prototype
- Add more tests for …
> Create gov.uk prototypes on the cloud platform

- pkg/commands/version.go
- pkg/environment/namespace.go
- pkg/environment/templateEnvironment.go
- pkg/environment/yesNoValidator.go
This change adds a "review-after" annotation to 00-namespace.yaml if the user says it's a sandbox/scratch namespace.
depends on https://github.com/ministryofjustice/cloud-platform-environments/pull/4272
- If env=="development" don't ask if it's prod
- Allow user to answer yes/no, instead of true/false
- Set "review-after" annotation for sandbox envs.
> I had to revert [this PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/4272) because it breaks the CLI until **this** PR is merged. Once the CLI has been updated, please merge [this replacement PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/4279)
> Add review-after annotation to scratch namespaces

- pkg/environment/templatePrototype.go
Remove Team Email question as it is not required as this defaults to platforms@digital.justice.gov.uk for all prototypes
> Remove Team Email question

- .github/workflows/build-release.yml
- cmd/cloud-platform/.goreleaser.yml
- pkg/commands/version.go
Overview
---
This change enables users of the `cloud-platform-cli` tool to use the popular mac package management tool brew. Users should be able to install the cli via a simple command `brew install ministryofjusice/cloud-platform-tap/cloud-platform-cli`. This change relies on two external entities:
- first that a repository called `homebrew-cloud-platform-tap` exists and contains a directory called `Formula`
- second that a personal access token secret exists (in this repository) called `HOMEBREW_GITHUB_CLI`.
> Add homebrew tap to Goreleaser

- .github/workflows/build-release.yml
I'm hoping this is the cause of the lack of mac arm build in goreleaser.
> Bump GH actions to go 1.16

- cmd/cloud-platform/.goreleaser.yml
- pkg/commands/version.go
The last build release failed with error 
```release failed after 0.75s error=hook failed: go mod download: exit status 1; output: go: github.com/MakeNowJust/heredoc@v1.0.0: reading https://gocenter.io/github.com/%21make%21now%21just/heredoc/@v/v1.0.0.mod: 405 Not Allowed```
"gocenter" is deprecated. go module uses https://proxy.golang.org,direct as default. Hence remove setting GOPROXY.
> Remove GOPROXY

- pkg/terraform/terraform.go
Related to: https://github.com/ministryofjustice/cloud-platform/pull/3049 
- Add kubectl config use-context before doing a terraform plan. This will fix setting wrong context for kubectl commands
- Check kubectl current context and compare with the workspace before doing plan and apply
- Split workspaces with spaces instead of newline - If the current workspace has * and it is the expected one. For example, if the current workspace is manager, the workspace list give `* manager` and when it compares with "manager" it fails.
> Set current-context of cluster, compare the cluster context with workspace 

- Dockerfile
- pkg/commands/version.go
This is to keep consistency with the tools image so all the cloud platform terraform code uses 0.14.8 version
> Update terraform binary to 0.14.8

- go.mod
- pkg/environment/migrate.go
- pkg/environment/migrate_test.go
ElasticSearch modules and IAM roles required certain changes which must be done by the user. This PR performs a recursive grep within the namespace to ensure the namespace is not using it. If they are using it, a warn is displayed saying to contact  Cloud-Platform.
Adding HCL parsing, so once identified terraform file with elastic-search module perform the following add/update:
```
irsa_enabled          = "true"
assume_enabled        = "false"
```
> Added ElasticSearch and IAM validation

- pkg/commands/version.go
- pkg/environment/migrate.go
APPLY_PIPELINE_SKIP_THIS_NAMESPACE file is also added to the live folder but we don't want that. This is happening because of the order we are running the functions.
This PR fixes that problem.
> Fix bug: APPLY_PIPELINE_SKIP_THIS_NAMESPACE file in thr wrong folder

- pkg/github/release/release.go
Not ideal that it is hard-coded, but this is just an error message, but perhaps the priority is to be helpful to the user, than maintainability if we change the repo name or something.
> Link to a web page (for humans), rather than the API

- go.mod
- go.sum
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/document.go
This provides a fairly basic package to enable callers to generate a client-go clientset and interface. It's structured in its own package to allow users to easily mock and test usage.
> feat(client): :sparkles: Add client package to provide easy Kubernetes auth

- .github/workflows/build-release.yml
- Dockerfile
- pkg/commands/version.go
There is a build error in the `sigs.k8s.io/json/internal/golang/encoding/json` that is fixed by updating to Go 1.17.x
> build: :bug: Upgrade version of Go when building and releasing

- pkg/cluster/cluster.go
- pkg/cluster/node.go
- pkg/cluster/node_test.go
- pkg/commands/version.go
- pkg/recycle/drain.go
- pkg/recycle/recycle.go
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/3361 and relates to the requirement to only recycle nodes from the default node group. This decision was taken as Prometheus appears to take over ten mins to restart, and for reasons we cannot mitigate that.
It also contains a catch for failing nodes, or nodes in a "not ready" state.
> Amend only the default node group and add more protection

- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
- pkg/cluster/node.go
- pkg/cluster/node_test.go
- pkg/commands/bumpModules.go
- pkg/commands/cluster.go
- pkg/commands/version.go
- pkg/recycle/drain.go
- pkg/recycle/recycle.go
This PR catches a condition where a user either passes incorrect aws credentials or nothing at all. By removing the need to specify an AWS profile, we rely on the end user to pass the AWS credentials via environment variables.
> Catch incorrect AWS credentials passed to a session

- pkg/commands/environment.go
- pkg/environment/common.go
- pkg/environment/templateEnvironment.go
- pkg/environment/templateEnvironment_test.go
- pkg/environment/templatePrototype.go
- pkg/environment/templatePrototype_test.go
This is to create files in the existing prototype repo, instead of creating new GitHub repo
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/3457
Also, Update the environment package, this is to create all the new namespaces in the "live" repo
> Prototype cli

- pkg/commands/cluster.go
- pkg/commands/version.go
- pkg/environment/migrate_test.go
cobra return exit(0) when returned from sub-command. https://github.com/spf13/cobra/issues/1156
Use contextLogger.Fatal which returns exit(1) to catch the error when run on CI.
Closes: https://github.com/ministryofjustice/cloud-platform/issues/3560
> Return fatal

- Dockerfile
- pkg/commands/version.go
This is to fix pipeline error `'invalid apiVersion client.authentication.k8s.io/v1alpha1'
AWS CLI has an issue with the versions less that 2.6.3 when executing `aws eks update-kubeconfig` and throw invalid apiVersion. This PR is to upgrade the cli and thereby fixing it
> Upgrade aws cli to fix invalid apiVersion

- .github/dependabot.yml
Enables Dependabot for Docker, Go, and GitHub Actions.
> Enable Dependabot for cloud-platform-cli

- .gitignore
- README.md
- cmd/cloud-platform/.goreleaser.yml
- makefile
- pkg/commands/version.go
Overview
---
This PR removes the requirement to "bake" the tag/release version into code. By utilising the Go build flags we can pass the version into the binary at build-time.
Pros:
- No more accidental version mismatches
- Easier instructions for new contributors
Cons:
- When developing locally, we'll have to either pass the version at build/run time or always use the `--skip-version-check` flag.
> Change how we version the cli binary

- pkg/environment/common.go
- pkg/environment/lowercaseStringValidator.go
- pkg/environment/templateEnvironment.go
Overview
---
This PR adds a conditional statement that changes the base namespace directory depending on the end-user's answer to the "Name of your Environment?" question. Previously, this assumed live-1 and specified so in a constant. This value will now be a global variable in the `environment` package, which is passed to multiple functions.
Connects to https://github.com/ministryofjustice/cloud-platform/issues/4030
> Add conditional for dev-alpha cluster

- .github/workflows/go-vet-lint-deps.yaml
- .github/workflows/run-tests.yml
- README.md
It occurred to me that we don't perform any linting on PR's. We should follow the opinionated best practice of the popular linter [gofumpt](https://github.com/mvdan/gofumpt), which enforces stricter formatting than gofumpt.
This PR also adds codecov uploads so we get an understanding of the test coverage in our codebase and outputs the tests in a nicer format.
> Add linting and improved testing

- .dockerignore
- install.sh
This PR creates a sample install script to enable users to install `cloud-platform-cli` using a curl command, such as:
```sh
curl https://raw.githubusercontent.com/ministryofjustice/cloud-platform-cli/66294a747d40f9d966ea844809b55a70631ddd39/install.sh | sh
```
This means a user can install the appropriate OS/Architecture version of cloud-platform-cli without having to know beforehand what version to use.
Currently supports Darwin/Linux and amd64/arm64; and will exit if the CLI is already installed via Homebrew.
> Create a sh install script to simplify installing cloud-platform-cli

- .github/workflows/build-docs.yml
- cmd/cloud-platform/main.go
- doc/cloud-platform.md
- doc/cloud-platform_completion.md
- doc/cloud-platform_completion_bash.md
- doc/cloud-platform_completion_fish.md
- doc/cloud-platform_completion_powershell.md
- doc/cloud-platform_completion_zsh.md
- pkg/commands/decodeSecret.go
This PR contains three things, as the title suggests: 
- It creates an alias for the `cloud-platform` command, `moj-cp`.
- It adds the first round of automatic completions to the `cloud-platform` command. This will allow users to perform tab completions when performing commands, such as `cloud-platform environment`. If this is useful, we can expand this offering to all popular commands.
- It improves how you generate the documentation. We introduced automatic document generation in the 1.18 release, and it worked by specifiying a `--generate-docs` flag that was hidden to the end user. This caused issues when leading with a global/parent flag. For example, when running `cloud-platform --skip-version-check version` it would initiate an exit 1 with the error:
```bash
flag provided but not …
```
> Aliases, completions and improved document generation

- .dockerignore
- .github/workflows/code-analysis.yml
- .github/workflows/docker-tests.yaml
- .github/workflows/go-tests.yaml
- .gitignore
- README.md
- docker-test.yaml
This PR contains two things:
- A method to test the Dockerfile structure works, with an accompanying GitHub action and documentation.
- Linting and other touchups I noticed were needed when working in the repository.
Why do we want to merge?
- Asserting the Dockerfile build and structure will allow us to make faster decisions on dependabot PR's.
- The repository looks cleaner with linting and better naming conventions.
> Test the Dockerfile Structure 

- pkg/terraform/terraform.go
This was missed off and is required as the method doesn't respect the `sensitive` label, which results in printing secrets to stdout (not good for shared pipelines).
> Add stdout method call to terraform output

- .github/workflows/build-release.yml
- .goreleaser.yml
goreleaser pipeline error when running the docker build, reverting back to old build method to unblock release of 1.22.3, and to investigate error separately
> fix(goreleaser): Revert goreleaser docker build

- pkg/environment/namespace.go
patch the current implementation of [creating templated environments by passing an answer file](https://github.com/ministryofjustice/cloud-platform-cli/blob/main/pkg/environment/templateEnvironment.go#L303-L304) which doesn't recognise camelcase fields
> Add struct tags to map keys in answers yaml to fields in Namespace struct

- pkg/github/client.go
By default, the method returns only 30 files in that PR. Sometimes, when doing bulk PR, all namespace changes in the PR are not listed. This PR increase the default results to return 100(which is max).
> Increase results page to 100

- go.mod
- go.sum
- pkg/environment/environmentApply.go
- pkg/util/filesystem.go
- pkg/util/filesystem_test.go
- pkg/util/util.go
- pkg/util/util_test.go
This PR 
- ignore matching strings containing `|user|arn|ssh-rsa|clientid` and also ignores kubernetes_secret.
- Check for yaml files before doing kubectl on a namespace
> Reduce strings to be redacted in terraform output

- doc/cloud-platform_environment.md
- doc/cloud-platform_environment_plan.md
- pkg/commands/environment.go
- pkg/environment/applier.go
- pkg/environment/environmentApply.go
`--dry-run` was deprecated without a value in [kubectl 1.18](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#feature-9), so this adds the `client` value. `client` just prints the object locally.
>You can use the --dry-run=client flag to preview the object that would be sent to your cluster, without really submitting it.
> Update kubectl --dry-run to kubectl --dry-run=client

- pkg/commands/environment.go
- pkg/environment/environmentApply.go
- pkg/util/util.go
- pkg/util/util_test.go
This PR adds a RedactedEnv function to `util` package for relaxing terraform environment command output to redact only `hex` values.
> Add RedactedEnv function to utils package

- pkg/environment/environmentApply.go
- pkg/util/filesystem.go
Do soft return with false if yaml file doesnot exists. For PRs which has namespace deletion, we dont need to error if the yaml file doesnot exists.
> Skip namespace deletion PRs for terraform plan

- doc/cloud-platform.md
- doc/cloud-platform_pipeline.md
- doc/cloud-platform_pipeline_delete-cluster.md
- pkg/commands/cluster.go
- pkg/commands/commands.go
- pkg/commands/pipeline.go
- pkg/pipeline/pipeline.go
- pkg/util/clusterName.go
- pkg/util/clusterName_test.go
- testdata/help.ct
Using one command you can delete a cluster via the pipeline
`cloud-platform pipeline delete-cluster --cluster-name <name>`
The pipeline can delete 5 clusters simultaneously
Future PRs:
- post failures to `lower-priority-alarms`
- automate deleting clusters at the end of the week (list and then delete) (another job within the pipeline maybe?)
> feat: 🎸 add pipeline & pipeline delete-cluster command

- .github/dependabot.yml
- Dockerfile
- The cluster is in k8s 1.24 and hence as per skew policy we cant go beyond 1.25. As it is tricky to downgrade the kubectl library, pin the version to the 0.26 and not upgrade. The 0.26 library will have less breaking things to work with 1.24 cluster than a 0.29 version (latest). Update the pinned dependencies when the cluster is upgraded.
- Update dockerfile to match the current cluster version
> Ignore kubectl dependency bump

- go.mod
Our dockerfile is set to go 1.21, there is no reason to stay on go.19
> chore: 🤖 upgrade go version 1.19 -> 1.21

- Dockerfile
- docker-test.yaml
Debian is bigger but it'll be cached by concourse but is a lot easier to work with and avoids the random DNS breakages associated with alpine
```
debian                                                    bookworm-20240211-slim  97.1MB 
alpine                                                     3.19                                       7.73MB
```
> chore: 🤖 remove alpine in favour of debian

- .github/workflows/build-adhoc-release.yml
In order to proceed with the split components infrastructure work we need the ability to create a new cloud-platform-cli image seperate to the production version so we can test our cluster builds.
Ref https://github.com/ministryofjustice/cloud-platform/issues/5365
What this PR does is add a new github action which takes `branch` as an option when you manually run the action. It will then build the image based off that branch/ref and tag a new image with it. This way we don't break the production release of the cli.
> Add support for building adhoc images from git refs

- pkg/cluster/cluster.go
- pkg/cluster/node.go
- pkg/util/testutils.go
We were hitting errors calling the Kube API so quickly with the same request twice
```
time="2024-08-28T13:05:19Z" level=fatal msg="oldest node is tainted with monitoring-node and can't find a new node" subcommand=recycle-node
```
We already have all the nodes, we can pass this directly to the right function
> perf: ⚡️ call GetAllNodes once

- pkg/environment/slackChannelValidator.go
- pkg/environment/slackChannelValidator_test.go
This commit relates to
https://github.com/ministryofjustice/cloud-platform-cli/issues/604 and
fixes the lack of numbers in the validation regex. The commit also
contains a test table.
> :bug: Fix regex bug in slack validator

- pkg/environment/createPR.go
- pkg/environment/isRdsVersionMismatched.go
- pkg/environment/isRdsVersionMismatched_test.go
- pkg/github/client_test.go
> fix: 🐛 static code error and mock tests

- pkg/environment/updateVersion.go
- macos and linux sed commands behave differently for in file replace `-i`
- use a cross compatible command
> fix: 🐛 cross-compatibility between macos and linux sed cmds

- pkg/release/release.go
This pull request Changes the update messaging to refer to the user guide instead of explicitly using Homebrew, this is because the Analytical Platform ship this tool as part of our cloud development environment base image and is misleading for users.
Signed-off-by: Jacob Woffenden <jacob.woffenden@digital.justice.gov.uk>
> 📝 Update the update messaging

- pkg/environment/createPR.go
- pkg/environment/updateVersion.go
- pkg/github/client.go
- pkg/github/client_iface.go
- pkg/github/client_test.go
Currently, duplicate PRs are being created when the pipeline runs overnight/ over the weekend and hits the same error, this creates more work for the reviewer.
Skip PR creation and posting to slack if a PR already exists
> feat: 🎸 skip creating a pr for rds drift if one already exists

- doc/cloud-platform_terraform_apply.md
- doc/cloud-platform_terraform_check-divergence.md
- doc/cloud-platform_terraform_plan.md
- pkg/commands/terraform.go
- pkg/environment/createPlanSummary.go
- pkg/environment/createPlanSummary_test.go
- pkg/terraform/terraform.go
- pkg/terraform/terraform_test.go
1/2 PRs
This PR outputs the plan file for the `cloud-platform terraform plan` command and takes a plan file to as an argument to be used in a `cloud-platform terraform apply`.
The next PR will push the plan file from the pipeline to our s3 bucket and respectively pulls the correct file from s3 to be used in `terraform apply`, these changes will be in our [`terraform-concourse` repo here](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/429)
- add flags to indicate whether we should output/ use a plan file
- output plan in the dir that the `terraform plan` is running from
- use plan file in terraform apply
- fix environments plan comment format
> Pass out the plan file from tf plan cmd AND pass it into the tf apply cmd

- pkg/commands/pipeline.go
concourse runs on the default ng, so it makes sense that you can't delete that node group whilst running the command from the same node group
closes https://github.com/ministryofjustice/cloud-platform/issues/6038
> chore: 🤖 prevent concourse default ng from being deleted

- pkg/cluster/delete_utils/utils.go
- pkg/cluster/delete_utils/utils_test.go
- pkg/environment/applier.go
- pkg/environment/apply.go
- pkg/environment/destroy.go
- pkg/environment/plan.go
- pkg/util/concurrent.go
- pkg/util/concurrent_test.go
- pkg/util/util.go
- pkg/util/util_test.go
Continue chunking and batching namespaces across different pipelines but within those pipelines run the applies concurrently.
This PR covers:
- if the pipeline fails a namespace apply, then fail silently but collect all the errored namespaces and log them so we can inspect them if we need
- rewrite the namespace apply so we can take advantage of go routines and speed up apply pipelines
- remove duplicate call to plan
- explicitly pass a namespace arg to `destroyNamespace`, `planNamespace` and `applyNamespace` to fix a bug where incorrectly structs were accessed during parallel runs
- move contains fn from `deleteutils` to `util`
- project test coverage increased from 68.5% -> 72.0%
performance results:
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environment …
> perf: ⚡️ run apply namespaces in apply pipeline concurrently

- pkg/environment/apply.go
- incrementally lower the amount of concurrent terraform commands we are running until concourse workers are not spiking too heavily
> perf: ⚡️ concourse worker cpu is spiking too high

- pkg/environment/apply.go
- pkg/util/util.go
- we were seeing git lock errors when trying to pull concurrently and so reverted to doing a pull only once
- safely ignore the error and pull on every apply
> fix: 🐛 git pull err that was preventing pulling on every apply

- doc/cloud-platform_pipeline.md
- doc/cloud-platform_pipeline_create-custom-cluster.md
- doc/cloud-platform_pipeline_test-custom-cluster.md
- pkg/commands/pipeline.go
- pkg/pipeline/pipeline.go
- Adds two new commands:
- `create-custom-cluster` - creates a custom cluster using the `custom-cluster` pipeline
- `test-custom-cluster` - runs integration tests against a cluster
- refactored a parameter function to be more generic
-
> feat: add create-custom-cluster and test-custom-cluster

- .github/workflows/go-tests.yaml
- scripts/auto_approve.sh
- Update the auto approve script to skip commenting on the PR if `APPLY_PIPELINE_SKIP_THIS_NAMESPACE` is the only changed files in the PR 
- Update `go-test.yaml` for deprecated github action version
```
[go-test This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
- fix test log with the same name in different OS
```
go-test (macos-latest)
Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
> fix: Update Auto Approve Script

- pkg/cluster/delete.go
- fix below error
```
Please delete these namespaces, and any associated AWS resources, before destroying this cluster: [cloud-platform-github-teams-filter]  subcommand=delete-cluster
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/eks-create-test-destroy/jobs/destroy-cluster/builds/292#L674a01a7:6
> fix: allow pipeline to delete gh team filter namespace

- pkg/environment/isRdsVersionMismatched.go
- pkg/environment/updateVersion.go
- version output has changed
- also add compatibility for aurora drift
> fix: 🐛 syntax changes from the aws cli

- pkg/environment/businessUnitValidator.go
- Update `businessUnitValidator` so users can input the correct `business-unit`
- Reference:
- https://technical-guidance.service.justice.gov.uk/documentation/standards/documenting-infrastructure-owners.html#tags-you-should-use
- https://github.com/ministryofjustice/aws-root-account/blob/814abc38c55f54c15056855e7a9c746b9c8b8fd8/management-account/terraform/organizations-policy-tags.tf#L25-L35
> chore: update business unit validator

- pkg/environment/templatePrototype.go
- pkg/prototype/templatePrototypeDeployment.go
This change relates to issue [#6769](https://github.com/ministryofjustice/cloud-platform/issues/6769)
The authentication on the Prototype sites is there so citizens don't mistake them for real government services. To stop users from mistaking it for secure authentication, we're removing the ability to set custom usernames and passwords as values are displayed in plaintext in a public GitHub repository. The new credentials are set to:
```
USERNAME: prototype
PASSWORD: notarealwebsite
```
This change has been built and tested by creating a local version of the CLI to ensure the changes work as intended.
This has also been tested using the integration tests. All tests passed:
```
Integration tests: 
=== RUN   TestCreatePrototype
--- PASS: TestCreatePrototype (0.58s)
…
=== RUN …
```
> Remove the ability to set username and password for prototype and replace with defaults

- cmd/cloud-platform.go
- doc/cloud-platform_environment.md
- doc/cloud-platform_environment_rds-drift-checker.md
- pkg/cluster/create_test.go
- pkg/commands/environment.go
- pkg/decodeSecret/decodeSecret.go
- pkg/decodeSecret/decodeSecret_test.go
- pkg/environment/apply.go
- pkg/environment/createPR.go
- pkg/environment/isRdsVersionMismatched.go
- pkg/environment/isRdsVersionMismatched_test.go
- pkg/environment/namespace.go
- pkg/environment/rdsDriftChecker.go
- pkg/environment/updateVersion.go
- pkg/terraform/utils_test.go
- pkg/util/filesystem.go
- pkg/util/filesystem_test.go
- This PR introduces functionality to automatically detect and fix Terraform RDS engine version drift across cloud-platform-environments repo, using CSV input from either S3 or a local file.
- New CLI command: 
```
cloud-platform environment rds-drift-checker <file-location>
Supported formats:
- s3://bucket/path/to/file.csv
- file://local/path/to/file.csv (for testing/debugging)
```
- `RdsDriftChecker`:
- Parses CSVs with namespace + error messages
- Groups errors per namespace
- Detects RDS version downgrade mismatches using `IsRdsVersionMismatched()`
- Applies fixes by updating Terraform files
- Opens a PR for each namespace
- Handles both hardcoded and variable-based db_engine_version definitions
- Ensures changes are scoped to the namespace only
- Skips if an open PR already exists …
> feat: run rds drift checker on merged namespace rds error file

- pkg/cluster/create.go
Fix for [failing pipeline create cluster](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/create-cluster/jobs/create/builds/496#L67dae7bd:98311:98316).
> Removing obsolete variable that breaks pipeline

- pkg/environment/createPR.go
- pkg/environment/isRdsVersionMismatched.go
- pkg/environment/rdsDriftChecker.go
- pkg/environment/updateVersion.go
- Some RDS downgrade error comes as below
```
Cannot find upgrade path from 14.19 to 14.17.,   with module.rds-instance.aws_db_instance.rds,
```
- for the extra dot in `14.17.`, current code cannot trim it and hence it cannot match the version in the environment repo tf code
- Update `removeInputStr` function to trim the version
-----
- Add and keep the debug log for future troubleshooting
----
- Skip counting below error as critical failures to reduce alert noise in lower priority channel.
```
- terraform is failing but it doesn't look like a rds version mismatch
- a PR is already open for this namespace
```
----
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/7160
> fix: Update RDS drift checker

- pkg/decodeSecret/decodeSecret.go
- pkg/decodeSecret/decodeSecret_test.go
- Fixes string encoding in secrets
To test:
1. Checkout this branch
2. Run `make build`
3. Run `./cloud-platform-1.45.0-dirty decode-secret -n mikebell-test -s test-secret --skip-version-check`
4. You should see the secret `<badger<>`
> fix: re-encode escaped characters in secrets

- pkg/commands/terraform.go
in the event of terraform step error, we have been doubling the error message output to console. contextLogger return was also unredacted. this change resolves these issues.
relates to ministryofjustice/cloud-platform#7549
> fix: 🐛 tf init, plan, apply error duplicate console output

- .github/workflows/build-release.yml
This PR updates the GitHub Actions workflow to ensure that the Docker build and push job only runs if the GoReleaser build completes successfully.
- Added `needs: build` to the `docker` job.
- Ensures the “Build container and push to DockerHub” job is skipped automatically if the GoReleaser build fails.
- Prevents publishing partial or broken releases.
Previously, the Docker build would run even if the GoReleaser step failed, potentially leading to inconsistent or incomplete release artifacts. This change ensures dependent builds are only triggered after a successful GoReleaser release.
> Add dependency to skip Docker build if GoReleaser build fails
