ministryofjustice/cloud-platform-cli

- pkg/environment/common.go
- pkg/environment/templatesRds.go
Output to a file. For that I had to check: 
- Are we in a git repository that it named cloud-platform-environments, if not ask user if he want to continue outputting in the screen
> Adding posibility to output to a file

- README.md
This is a stub which we can improve as we add tests, multi-platform
build scripts, etc.
> Add a "Develop" section to the README.md

- .gitignore
- README.md
- makefile
- pkg/environment/templateEnvironment_test.go
At this point, there is only a single stub test,
but the makefile will run any tests that exist.
> Add a makefile to compile and to run tests

- .gitignore
- pkg/commands/environment.go
- pkg/commands/version.go
- pkg/environment/common.go
- pkg/environment/namespace.go
- pkg/environment/namespace_test.go
- pkg/environment/prompts.go
- pkg/environment/repoEnvironment.go
- pkg/environment/repoEnvironment_test.go
- pkg/environment/templateEnvironment.go
- pkg/environment/templateEnvironment_test.go
- pkg/environment/templatesRds.go
- pkg/environment/templatesRds_test.go
- pkg/environment/testutils.go
* Simplify the RDS creation
* Add new classes and test utils
* Rearrange the code to put as much as possible into testable functions
* Add tests for RDS & Environment creation
co-authored with @poornima-krishnasamy
> Refactor the code to make it more testable

- .github/workflows/go.yml
This github actions run the tests in these three platforms and build the binary. Tested in own fork
> Github actions to run tests in Linux, Windows and OSX

- pkg/commands/environment.go
- pkg/environment/templateEnvironment.go
- pkg/environment/templatesEcr.go
- pkg/environment/templatesEcr_test.go
fixes https://github.com/ministryofjustice/cloud-platform/issues/2060
co-authored with @vijay-veeranki
> Add an "ecr create" function to the cli tool

- pkg/commands/version.go
> bump version to 1.4.7

- pkg/commands/version.go
> bump cli version to v1.4.8

- pkg/commands/version.go
I forgot to do this when I created version 1.4.10
> Fix version number

- pkg/commands/version.go
- pkg/environment/templateEnvironment.go
- pkg/environment/templateEnvironment_test.go
depends on https://github.com/ministryofjustice/cloud-platform-environments/pull/2976
related to https://github.com/ministryofjustice/cloud-platform/issues/2224
related to https://github.com/ministryofjustice/cloud-platform/issues/2212
> Add ingress.tf to all new namespaces

- .github/workflows/sonar-scan.yml
This will run sonar qube scan on the PR's and report it to "https://sonarqube.cloud-platform.service.justice.gov.uk/projects".
This is related to [2117](https://github.com/ministryofjustice/cloud-platform/issues/2117)
> Sonar qube scan git-hub action

- pkg/environment/templateEnvironment.go
This was the only question that I was not sure about answering.
It seems pretty important to get the permissions right too, so extra clarity here seems useful.
> Clarify the purpose of what the GitHub team

- Dockerfile
- pkg/terraform/logger.go
- pkg/terraform/main.go
- Update Dockerfile to make everything smaller (faster pull from concourse and faster execution)
- Add logger capability to REDACT password, tokens, webhooks, etc
> Added logger and updated Dockerfile

- pkg/commands/version.go
- pkg/terraform/utils.go
- More directories to the apply/plan pipeline
- pushed version
> adding more dirs to apply pipeline

- pkg/terraform/terraform.go
terraform plan with -detailed-exitcode returns error with exit status 2 if there is a drift. Hence the output has to be captured when returning error and printed
> Fix terraform divergence output

- pkg/commands/version.go
- pkg/terraform/utils.go
EKS was recently moved to a new location within the infrastructure repo
> New path for EKS

- README.md
CLI is for more than just the CP team
> Change readme description

- pkg/commands/version.go
- pkg/terraform/utils.go
As we now updated our terraform directory structure
> Updated the dirsAllowed list

- pkg/commands/version.go
Release tag for this PR: https://github.com/ministryofjustice/cloud-platform-cli/pull/101
> Bump tag to build release

- .github/workflows/run-tests.yml
- go.mod
- go.sum
- pkg/kubecfg/githubTeams.go
Fixes
https://github.com/ministryofjustice/cloud-platform-cli/security/dependabot/go.mod/github.com%2Fdgrijalva%2Fjwt-go/open
> Replace vulnerable jwt-go package

- pkg/environment/migrate.go
* only change the correct module
> couple fixes for the migrate command

- Dockerfile
Tools image pr:
https://github.com/ministryofjustice/cloud-platform-tools-image/pull/87/files
> Update cli image inline with tools-image

- pkg/commands/version.go
This version has updated docker file
> Create new version

- pkg/commands/version.go
- pkg/environment/templatePrototype_test.go
- pkg/kubecfg/fixtures/kubeconfig.yml
- pkg/terraform/cloud-platform.go
Related to: https://github.com/ministryofjustice/cloud-platform/issues/3676
> Remove live-1 reference from terraform plan and apply commands

- .github/workflows/code-analysis.yml
until we figure out the security of its token
> remove Sonar scan for now

- pkg/util/util_test.go
Add missing tests from the utils package.
> Add unit tests for utils package

- pkg/environment/common.go
- pkg/environment/templateEnvironment.go
When the environment is specified as beta
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/4121
> Create namespace in live-2 repo

- .github/workflows/build-release.yml
- .goreleaser.yml
- Dockerfile-goreleaser
updating the build-release pipeline to allow goreleaser to build and publish binary to dockerhub and update slack channel on completion
> feat(goreleaser): Update build-release pipeline

- pkg/environment/rdsEngineValidator.go
- pkg/environment/templatesRds.go
- pkg/environment/templatesRds_test.go
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4057
> Add prompt to select rds engine version and generate appropriate rds file

- .github/workflows/build-release.yml
.goreleaser.yaml > .goreleaser.yml
> fix(workflow): Fix typo of file name extension

- pkg/environment/environmentApply.go
This PR ignores applying a namespace if the folder is not available. The PR maybe raised to remove the namespace which will be handled in seperate command
This PR also ignores applying terraform if the namespace doesnot contain resources folder.
> Ignore namespace and resources from applying if not in main branch

- pkg/environment/environmentApply.go
- pkg/environment/environmentApply_test.go
- pkg/util/filesystem.go
- pkg/util/filesystem_test.go
- Add method IsFilePathExists. This is to fix erroring when `resources` folder doesnot exists
- Fix terraform folder exists condition, some cleanup on tests
> Fix terraform folder check

- .github/workflows/go-vet-lint-deps.yaml
https://github.com/dominikh/staticcheck-action#usage
> Update version for staticcheck

- doc/cloud-platform_cluster_recycle-node.md
- pkg/commands/cluster.go
- pkg/recycle/recycle.go
- add flag for DrainOnly under recycle cmd
> feat: 🎸 add drain only flag to recycle-node cmd

- pkg/environment/githubTeamNameValidator.go
- pkg/environment/namespaceNameValidator.go
- pkg/environment/templateEnvironment_test.go
closes: https://github.com/ministryofjustice/cloud-platform/issues/5115
> Add numerals to namespace and githubTeam input

- Dockerfile
Related to: https://github.com/ministryofjustice/cloud-platform/issues/5156
> Add python to run lambda during terraform operations

- pkg/cluster/delete.go
> chore: 🤖 whitelist label-pods

- .github/workflows/build-docs.yml
- .github/workflows/build-release.yml
- .github/workflows/go-tests.yaml
- .github/workflows/go-vet-lint-deps.yaml
- Dockerfile
- go.mod
- go.sum
- pkg/terraform/terraform_test.go
This _should_ fix the broken tests in this repository.
> ⏫ Upgrade Terraform & Go versions + a Go Mod Tidy

- doc/cloud-platform_environment_apply.md
- doc/cloud-platform_environment_destroy.md
- doc/cloud-platform_environment_plan.md
- pkg/commands/environment.go
- pkg/environment/applier.go
- pkg/environment/createPR.go
- pkg/environment/environmentApply.go
- pkg/environment/isRdsVersionMismatched.go
- pkg/environment/isRdsVersionMismatched_test.go
- pkg/environment/updateVersion.go
- pkg/github/client.go
- pkg/github/client_iface.go
- pkg/slack/notifyUser.go
WHEN an env pipeline fails and that failure results from an RDS version mismatch causing a downgrade
THEN raise a PR updating the terraform to the current actual db version
THEN post that PR to ask
> feat: 🎸 if a tf apply fails b/c rds version drift, raise a pr

- doc/cloud-platform_environment_apply.md
- pkg/environment/environmentApply.go
> chore: 🤖 make error logging more useful

- doc/cloud-platform_environment_apply.md
- pkg/commands/environment.go
- pkg/environment/environmentApply.go
- when a build fails it should try and find the concourse user in the ask channel and @them instead skip as we don't need to post to ask
> style: 💄 rename IsPipeline -> IsApplyPipeline

- pkg/environment/applier.go
prs are failing with this
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/plan-live/builds/11544
> fix: 🐛 error from use json number

- pkg/release/release.go
https://mojdt.slack.com/archives/C57UPMZLY/p1727971782954069
> style: 💄 update inform user message

- .github/workflows/build-release.yml
https://goreleaser.com/deprecations/?h=depre#-rm-dist
> fix: 🐛 goreleaser cmd

- pkg/decodeSecret/decodeSecret.go
- pkg/decodeSecret/decodeSecret_test.go
relates to ministryofjustice/cloud-platform#6419
> test: 💍 check for secret json missing data key

- Dockerfile
- pkg/environment/apply_test.go
- scripts/auto_approve.sh
- Update the docker image to install opa
- Create new script which will be running in plan-live pipeline for auto approve
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/5996
> feat: Prepare for Pipeline Auto Approve

- scripts/auto_approve.sh
> fix: Fix auto approve script

- scripts/auto_approve.sh
- update the if block logic to check yaml file (and skip file can pass)
- update and improve the comment content
> chore: Update Auto Approve script

- pkg/slack/post.go
and link to some more relevant information about why we have the SKIP file for these scenarios
> style: 💄 make our namespace apply fail bot reminder kinder

- scripts/auto_approve.sh
- update github comment to prevent user from getting confusion
> chore: Update gh comment to prevent confusion

- .github/workflows/build-adhoc-release.yml
- .github/workflows/build-docs.yml
- .github/workflows/code-analysis.yml
- .github/workflows/docker-tests.yaml
- .github/workflows/go-tests.yaml
- .github/workflows/go-vet-lint-deps.yaml
> Pin actions

- pkg/environment/createPlanSummary.go
- pkg/environment/createPlanSummary_test.go
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections#creating-a-collapsed-section
> style: 💄 open the tf summary by default (increase visibility)

- pkg/commands/environment.go
relates to ministryofjustice/cloud-platform#6884
> chore: 🤖 remove kuberhealthy ns refs

- pkg/cluster/delete.go
relates to ministryofjustice/cloud-platform#6884
> chore: 🤖 remove kuberhealthy refs

- scripts/auto_approve.sh
- Updates the auto approve script to work with the new folder layout
- Provides more feedback when tests fail
> feat: update script to work with new folder layout

- pkg/cluster/node.go
Fixes failing recycle oldest node logic for recycle node overnight pipelines
relates to ministryofjustice/cloud-platform#7442
> fix: 🐛 fix logic for oldestNode function
